server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
leyou:
  jwt:
    secret: fuyao@Login(Auth}*^31)&wangb% #登录校验的密钥(盐)
    pubKeyPath: F:\\tmp\\rsa\\rsa.pub #公钥地址
    priKeyPath: F:\\tmp\\rsa\\rsa.pri #私钥地址
    expire: 30 #过期时间,单位分钟
    cookieName: FY_TOKEN
    cookieMaxAge: 30  #cookie的生存时间