server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fuyao
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 119.45.186.76
#  rabbitmq:
#    host: 119.45.186.76
#    username: fuyao
#    password: fuyao
#    virtual-host: /fuyao
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
