server:
  port: 10010
spring:
  application:
    name: fuyao-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
zuul:
  prefix: /api # 路由路径前缀