server:
  port: 10010
spring:
  application:
    name: fuyao-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    user-service: /user/** #用户微服务
    auth-service: /auth/**  # 授权中心微服务
fuyao:
  jwt:
    pubKeyPath: F:\\tmp\\rsa\\rsa.pub
    cookieName: FY_TOKEN
  filter:
    allowPaths:   #允许的路径
      - /api/auth
      - /api/user/register
      - /api/user/check